[profile.default]
remappings = [
  "v4-core/=lib/v4-core/src/",
  "v4-periphery/=lib/v4-periphery/src/",
  "forge-std/=lib/forge-std/src/"
]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
